name: stiebel_etron_warranty
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  url_launcher: ^6.1.10
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.0.18
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  #majascan: ^0.5.0
  json_annotation: ^4.8.0
  data_table_2: ^2.4.1
  dropdown_button2: ^2.0.0
  dio: ^5.4.3+1
  otp_text_field: ^1.1.3
  dropdown_textfield: ^1.0.8
  flutter_typeahead: ^4.3.7
  cached_network_image: ^3.2.3
  local_auth: ^2.1.6
  flutter_svg: ^2.0.5
  get: ^4.6.6
  flutter_localization: ^0.1.14
  nb_utils: ^6.1.3
  string_normalizer: ^0.2.0
  maps_launcher: ^2.2.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logolauch.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logolauch.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/icon/
    - assets/json/
    - assets/images/
    - assets/translations/
