var jsonActive={
  "pageIndex": 0,
  "pageSize": 0,
  "totalPages": 0,
  "totalData": 0,
  "listData": [
    {
      "staffCreate": "string",
      "createDate": "2024-06-26T13:37:12.925Z",
      "staffUpdate": "string",
      "updateDate": "2024-06-26T13:37:12.925Z",
      "status": 0,
      "id": 0,
      "serial": "string",
      "modelId": 0,
      "modelName": "string",
      "modelCode": "string",
      "categoryId": 0,
      "categoryName": "string",
      "categoryCode": "string",
      "price": 0,
      "yearManufacture": "string",
      "dateExportStock": "2024-06-26T13:37:12.925Z",
      "partnerId": 0,
      "partnerName": "string",
      "partnerCode": "string",
      "statusActive": 0,
      "customerIdActiveData": "string",
      "customerNameActiveData": "string",
      "sku": "string"
    },
     {
      "staffCreate": "string",
      "createDate": "2024-06-26T13:37:12.925Z",
      "staffUpdate": "string",
      "updateDate": "2024-06-26T13:37:12.925Z",
      "status": 0,
      "id": 0,
      "serial": "string",
      "modelId": 0,
      "modelName": "string",
      "modelCode": "string",
      "categoryId": 0,
      "categoryName": "string",
      "categoryCode": "string",
      "price": 0,
      "yearManufacture": "string",
      "dateExportStock": "2024-06-26T13:37:12.925Z",
      "partnerId": 0,
      "partnerName": "string",
      "partnerCode": "string",
      "statusActive": 0,
      "customerIdActiveData": "string",
      "customerNameActiveData": "string",
      "sku": "string"
    },
     {
      "staffCreate": "string",
      "createDate": "2024-06-26T13:37:12.925Z",
      "staffUpdate": "string",
      "updateDate": "2024-06-26T13:37:12.925Z",
      "status": 0,
      "id": 0,
      "serial": "string",
      "modelId": 0,
      "modelName": "string",
      "modelCode": "string",
      "categoryId": 0,
      "categoryName": "string",
      "categoryCode": "string",
      "price": 0,
      "yearManufacture": "string",
      "dateExportStock": "2024-06-26T13:37:12.925Z",
      "partnerId": 0,
      "partnerName": "string",
      "partnerCode": "string",
      "statusActive": 0,
      "customerIdActiveData": "string",
      "customerNameActiveData": "string",
      "sku": "string"
    }
  ]
};